server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-authorization-changelog.xml

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/skillbox
    username: ${DB_USERNAME:account}
    password: ${DB_PASSWORD:account}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${DB_SCHEMA:account}
    open-in-view: false

kafka:
  bootstrap-servers: 82.202.214.42:9094
  producer:
    retries: 3
  topic:
    partition-count: 3
    replication-factor: 1
    login: topic.login
    registration: topic.registration

