spring:
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: authorization
    password: authorization
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: true
    drop-first: true
    default-schema: authorization
    liquibase-schema: authorization
