apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-authorization
data:
  application.yml: |-

    spring:
      boot:
        admin:
          client:
            enabled: true
            instance:
              service-url: http://microservice-authorization:8080

      liquibase:
        enabled: true
        drop-first: false
        change-log: classpath:database-authorization-changelog.xml

      datasource:
        url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driverClassName: org.postgresql.Driver
        hikari:
          minimum-idle: 10
          maximum-pool-size: 50

      jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            format_sql: true
            default_schema: ${DB_SCHEMA}
        open-in-view: false

